<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-08-26 14:55

$extensionPath = t3lib_extMgm::extPath('cdn_resources');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_cdnresources_hook_postprocesshook' => $extensionClassesPath . 'Hook/PostProcessHook.php',
	'tx_cdnresources_service_configurationservice' => $extensionClassesPath . 'Service/ConfigurationService.php',
	'tx_cdnresources_service_extractionservice' => $extensionClassesPath . 'Service/ExtractionService.php',
	'tx_cdnresources_service_httpheaderservice' => $extensionClassesPath . 'Service/HttpHeaderService.php',
	'tx_cdnresources_service_replacementservice' => $extensionClassesPath . 'Service/ReplacementService.php',
	'tx_cdnresources_service_urlservice' => $extensionClassesPath . 'Service/UrlService.php',
);
?>